### ISSUE TITLE
Can you release corresponding names of  the genera/families/orders annotations in CUB_200_2011? 

### ISSUE THREAD

**Issue by woshiyanyan** [HCPLab-SYSU/HSE#6]
I'm doing some work on the  hierarchical representation，and the corresponding name of  the 122 genera, 37 families, and 13 orders annotations is very important to my work. Can you release it?

**Comment by sanjeelparekh** [comment]
@woshiyanyan  - I am also looking for the names of genera, families, orders etc for CUB. Were you able to find these? Please let me know. Thanks!

**Comment by ThomasNorr** [comment]
@woshiyanyan, @sanjeelparekh - I have the same issue, did you find them?
Thanks :)

**Comment by xiapeng1110** [comment]
@woshiyanyan @sanjeelparekh @Gnabe Hi, is there any progress? I have the same issue.

**Comment by lingyu123-su** [comment]
@woshiyanyan @sanjeelparekh @xiapeng1110 hello,have the same issue in my project, any one find them?Or is there another dataset contains these kind of infomation
thanks!
